title:  Schneier on Security
subtitle: 
permalink: schneier-on-security
author: Bruce Schneier
finished_at: 2010-02-09
rating: 8 # out of 10
review: |
  Pulls together recommendations of the Copenhagen Concensus, a meeting that asked what problems experts and policy-makers should address, given $50 billion to spend. Good material is covered, but it's not quite as engaging as Bjorn's previous hit.
synopsis: 
